services:
  ubuntu-vps:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: ubuntu-vps
    systemd: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cpus: 4.0
    mem_limit: 8g
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
    ports:
      - "127.0.0.1:2222:22"
      - "127.0.0.1:8080:80"
    restart: unless-stopped
    networks:
      vps-lan:
        ipv4_address: ${VPS_IP}
      vps-bridge:

networks:
  vps-lan:
    driver: macvlan
    driver_opts:
      parent: ${PARENT_IFACE}
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY}
  vps-bridge:
    driver: bridge
